import { Bullet, P, Revised, Section } from '@/components/Prose';
import { ScreenHeader } from '@/components/ScreenHeader';
import { Button } from '@/components/ui/button';
import { Icon } from '@/components/ui/icon';
import { Text } from '@/components/ui/text';
import { LEGAL, openExternal } from '@/lib/legal';
import { ExternalLink } from 'lucide-react-native';
import * as React from 'react';
import { ScrollView, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function PrivacyScreen() {
  const insets = useSafeAreaInsets();
  return (
    <View className="flex-1 bg-background" style={{ paddingTop: insets.top + 8 }}>
      <ScreenHeader title="Privacy Policy" />

      <ScrollView
        contentContainerStyle={{ paddingBottom: insets.bottom + 40 }}
        contentContainerClassName="gap-7 px-4"
      >
        <Section title="The short version">
          <P>
            Threadknot connects your phone to Threadknot servers that you run. Your code,
            conversations and agent output stay on those machines. We do not collect them, and
            with a local-network connection nothing you send passes through us at all.
          </P>
        </Section>

        <Section title="What stays on your device">
          <Bullet>
            Server addresses and access tokens for the servers you pair, stored in the iOS
            keychain / Android keystore and gated behind device biometrics.
          </Bullet>
          <Bullet>Your choice of which server is active, and per-server notification settings.</Bullet>
          <Bullet>
            Files you attach to a message, only for as long as it takes to upload them to your
            own server.
          </Bullet>
        </Section>

        <Section title="What the Threadknot relay sees">
          <P>
            The relay exists so a machine at home can be reached from outside your network, and
            so it can wake your phone. You only touch it if you pair a remote address.
          </P>
          <Bullet>An account identifier and the relay addresses you paired.</Bullet>
          <Bullet>
            A push notification token, used to deliver the alert that an agent is waiting on
            you. Notification text is generated by your own server.
          </Bullet>
          <Bullet>
            Connection metadata needed to route traffic — timestamps and byte counts, kept
            briefly for abuse prevention.
          </Bullet>
          <P>
            Relayed traffic is end-to-end encrypted between your phone and your machine. The
            relay forwards bytes; it cannot read a thread.
          </P>
        </Section>

        <Section title="What we never do">
          <Bullet>No advertising, ad identifiers, or ad networks.</Bullet>
          <Bullet>No selling or sharing of personal data with third parties.</Bullet>
          <Bullet>No behavioural analytics or session recording.</Bullet>
          <Bullet>No training of any model on your content.</Bullet>
        </Section>

        <Section title="Third parties">
          <P>
            Push delivery uses Apple Push Notification service and Firebase Cloud Messaging,
            because that is the only way a phone can be woken. Agent providers you connect on
            your own machine — Anthropic, OpenAI and others — receive whatever you send those
            agents, under their own terms. Threadknot is not a party to that exchange.
          </P>
        </Section>

        <Section title="Your rights">
          <P>
            You can delete everything the relay holds at any time from Settings → Account &amp;
            data, or by writing to {LEGAL.supportEmail}. Data on your own machines is yours to
            delete directly. Requests are answered within 30 days, and deletions complete within
            24 hours.
          </P>
        </Section>

        <Section title="Children">
          <P>Threadknot is a developer tool and is not directed at children under 13.</P>
        </Section>

        <View className="gap-3">
          <Button variant="outline" onPress={() => void openExternal(LEGAL.privacy)}>
            <Icon as={ExternalLink} className="size-4 text-foreground" />
            <Text>Read the full policy</Text>
          </Button>
          <Text className="text-xs text-muted-foreground">
            Questions about privacy: {LEGAL.supportEmail}
          </Text>
          <Revised date="8 August 2026" />
        </View>
      </ScrollView>
    </View>
  );
}
